config/routes.rb
FoxAppsRails::Application.routes.draw do

  resources :user_management

  match 'API10/jurisdiction_list', :controller => 'api10', :action => 'jurisdiction_list'
  match 'API10/jurisdiction_statute/:id', :controller => 'api10', :action => 'jurisdiction_statute'
  match 'API10/jurisdiction_statutes/:id', :controller => 'api10', :action => 'jurisdiction_statutes'
  match 'API10/content_pages/:name/get_all_page_blocks', :controller => 'api10', :action => 'get_all_page_blocks'

  get 'content_pages/', :controller => 'content_pages', :action => 'index'
  get 'content_pages/new', :controller =>'content_pages', :action => 'new'
  get 'content_pages/show/:id', :controller => 'content_pages', :action => 'show', :as => 'show_content_pages'
  get 'content_pages/edit/:id', :controller => 'content_pages', :action => 'edit', :as => 'edit_content_pages'
  post 'content_pages/create/', :controller => 'content_pages', :action => 'create_page', :as => 'create_content_pages'
  put 'content_pages/update/:id', :controller => 'content_pages', :action => 'update', :as => 'update_content_pages'
  delete 'content_pages/destroy/:id', :controller => 'content_pages', :action => 'destroy', :as => 'destroy_content_pages'

  get 'page_blocks/show/:id', :controller => 'page_blocks', :action => 'show', :as => 'show_page_blocks'
  get 'content_pages/:content_page_id/page_blocks/new', :controller => 'page_blocks', :action => 'new', :as => 'new_page_blocks'
  get 'page_blocks/edit/:id', :controller => 'page_blocks', :action => 'edit', :as => 'edit_page_blocks'
  post 'page_blocks/:content_page_id', :controller => 'page_blocks', :action => 'create', :as => 'create_page_blocks'
  delete 'page_content/show/:content_page_id/:id', :controller => 'page_blocks', :action => 'destroy', :as => 'destroy_page_blocks'

  get 'page_content/:content_page_id/page_block/new_block_person/', :controller => 'page_blocks', :action => 'new_block_person', :as => 'new_block_person'
  post 'content_pages/show/create_block_person', :controller => 'page_blocks', :action => 'create_block_person', :as => 'create_block_person'
  put 'content_pages/:content_page_id/page_block/update_block_person/:id', :controller => 'page_blocks', :action => 'update_block_person', :as => 'update_block_person'
  get 'page_content/:content_page_id/page_block/new_plain_text/', :controller => 'page_blocks', :action => 'new_block_plain_text', :as => 'new_block_plain_text'
  post 'content_pages/show/create_block_text', :controller => 'page_blocks', :action => 'create_block_text', :as => 'create_block_text'
  put 'content_pages/show/update_block_plain_text/:id', :controller => 'page_blocks', :action => 'update_block_plain_text', :as => 'update_block_plain_text'
  get 'content_pages/:content_page_id/page_block/:id/create_pic', :controller => 'page_blocks', :action => 'create_pic', :as => 'create_pic'
  put 'content_page/:content_page_id/page_block/:id/update_pic', :controller => 'page_blocks', :action => 'update_pic', :as => 'update_pic'

  get 'page_content/:content_page_id/move_up/:id', :controller => 'page_blocks', :action => 'move_up', :as => 'move_up_page_blocks'
  get 'page_content/:content_page_id/move_down/:id', :controller => 'page_blocks', :action => 'move_down', :as => 'move_down_page_blocks'


  resources :statute_types do
    resources :statutes
    resources :text_entries
  end

  match 'jurisdictions/geocode', :controller => 'jurisdictions', :action => 'geocode'
  resources :jurisdictions


  get "home/index"

  devise_for :users

  root :to => 'home#index'

end

app/models/statute.rb
class Statute < ActiveRecord::Base
  attr_accessible :name, :url, :statute_type_id, :jurisdiction_id
  belongs_to :statute_type
  belongs_to :jurisdiction
end

app/models/statute_type.rb
class StatuteType < ActiveRecord::Base
  attr_accessible :name, :name_slug
  has_many :statutes
  has_many :text_entries
end

app/controllers/statutes_controller.rb
class StatutesController < ProtectedApplicationController

  # GET /statutes
  # GET /statutes.json
  def index
    @statutes = Statute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statutes }
    end
  end

  # GET /statutes/1
  # GET /statutes/1.json
  def show
    @statute = Statute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @statute }
    end
  end

  # GET /statutes/new
  # GET /statutes/new.json
  def new
    @statute = Statute.new
    @statute_type = StatuteType.find(params[:statute_type_id])
    @statute.statute_type_id = @statute_type.id
    @jurisdictions = Jurisdiction.order('name')
    @form_action = "create"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @statute }
    end
  end

  # GET /statutes/1/edit
  def edit
    @statute = Statute.find(params[:id])
    @statute_type = StatuteType.find(params[:statute_type_id])
    @jurisdictions = Jurisdiction.order('name')
    @form_action = "update"
  end

  # POST /statutes
  # POST /statutes.json
  def create
    @statute = Statute.new(params[:statute])
    @statuteUpdate = StatuteType.find(params[:statute_type_id])
    @statute.statute_type_id = @statuteUpdate.id

    respond_to do |format|
      if @statute.save
        format.html { redirect_to statute_type_url(@statute.statute_type_id), notice: 'Statute was successfully created.' }
        format.json { render json: @statute, status: :created, location: @statute }
      else
        format.html { render action: "new" }
        format.json { render json: @statute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statutes/1
  # PUT /statutes/1.json
  def update
    @statute = Statute.find(params[:id])

    respond_to do |format|
      if @statute.update_attributes(params[:statute])
        format.html { redirect_to statute_type_url(@statute.statute_type_id), notice: 'Statute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @statute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statutes/1
  # DELETE /statutes/1.json
  def destroy
    @statute = Statute.find(params[:id])
    @statute_type_id = @statute.statute_type_id
    @statute.destroy

    respond_to do |format|
      format.html { redirect_to statute_type_url(@statute_type_id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/statutes_helper.rb
module StatutesHelper
end

app/views/statutes/_form.html.erb
<%= form_for([@statute_type, @statute], :url => {:action => @form_action}, :html => { :class => 'form-horizontal' } ) do |f| %>
  <% if @statute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statute.errors.count, "error") %> prohibited this statute from being saved:</h2>

      <ul>
      <% @statute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Statute</legend>
    <div class="form-group">
      <%= f.label :name, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :jurisdiction, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <% if 0 == 0%>
          <%= collection_select :statute, :jurisdiction_id,  @jurisdictions, :id, :name, {}, { :class => 'form-control' } %>
        <% else %>
            <%= raw @statute.jurisdiction.name %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :url, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :url, :class => 'form-control' %>
      </div>
    </div>

    <%= f.hidden_field :statute_type_id, :value => @statute.statute_type_id %>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit 'Submit', :class => "btn btn-primary" %>
      </div>
    </div>
  </fieldset>

<% end %>

app/views/statutes/edit.html.erb
<%= render 'form' %>

app/views/statutes/index.html.erb
<h1>Listing statutes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statutes.each do |statute| %>
  <tr>
    <td><%= statute.name %></td>
    <td><%= link_to 'Show', statute %></td>
    <td><%= link_to 'Edit', edit_statute_path(statute) %></td>
    <td><%= link_to 'Destroy', statute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Statute', new_statute_path %>

app/views/statutes/new.html.erb
<div class="well">
	<%= render 'form' %>
</div>

app/views/statutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @statute.name %>
</p>


<%= link_to 'Edit', edit_statute_path(@statute) %> |
<%= link_to 'Back', statutes_path %>