config/routes.rb
FoxAppsRails::Application.routes.draw do

  resources :user_management

  match 'API10/jurisdiction_list', :controller => 'api10', :action => 'jurisdiction_list'
  match 'API10/jurisdiction_statute/:id', :controller => 'api10', :action => 'jurisdiction_statute'
  match 'API10/jurisdiction_statutes/:id', :controller => 'api10', :action => 'jurisdiction_statutes'
  match 'API10/content_pages/:name/get_all_page_blocks', :controller => 'api10', :action => 'get_all_page_blocks'

  get 'content_pages/', :controller => 'content_pages', :action => 'index'
  get 'content_pages/new', :controller =>'content_pages', :action => 'new'
  get 'content_pages/show/:id', :controller => 'content_pages', :action => 'show', :as => 'show_content_pages'
  get 'content_pages/edit/:id', :controller => 'content_pages', :action => 'edit', :as => 'edit_content_pages'
  post 'content_pages/create/', :controller => 'content_pages', :action => 'create_page', :as => 'create_content_pages'
  put 'content_pages/update/:id', :controller => 'content_pages', :action => 'update', :as => 'update_content_pages'
  delete 'content_pages/destroy/:id', :controller => 'content_pages', :action => 'destroy', :as => 'destroy_content_pages'

  get 'page_blocks/show/:id', :controller => 'page_blocks', :action => 'show', :as => 'show_page_blocks'
  get 'content_pages/:content_page_id/page_blocks/new', :controller => 'page_blocks', :action => 'new', :as => 'new_page_blocks'
  get 'page_blocks/edit/:id', :controller => 'page_blocks', :action => 'edit', :as => 'edit_page_blocks'
  post 'page_blocks/:content_page_id', :controller => 'page_blocks', :action => 'create', :as => 'create_page_blocks'
  delete 'page_content/show/:content_page_id/:id', :controller => 'page_blocks', :action => 'destroy', :as => 'destroy_page_blocks'

  get 'page_content/:content_page_id/page_block/new_block_person/', :controller => 'page_blocks', :action => 'new_block_person', :as => 'new_block_person'
  post 'content_pages/show/create_block_person', :controller => 'page_blocks', :action => 'create_block_person', :as => 'create_block_person'
  put 'content_pages/:content_page_id/page_block/update_block_person/:id', :controller => 'page_blocks', :action => 'update_block_person', :as => 'update_block_person'
  get 'page_content/:content_page_id/page_block/new_plain_text/', :controller => 'page_blocks', :action => 'new_block_plain_text', :as => 'new_block_plain_text'
  post 'content_pages/show/create_block_text', :controller => 'page_blocks', :action => 'create_block_text', :as => 'create_block_text'
  put 'content_pages/show/update_block_plain_text/:id', :controller => 'page_blocks', :action => 'update_block_plain_text', :as => 'update_block_plain_text'
  get 'content_pages/:content_page_id/page_block/:id/create_pic', :controller => 'page_blocks', :action => 'create_pic', :as => 'create_pic'
  put 'content_page/:content_page_id/page_block/:id/update_pic', :controller => 'page_blocks', :action => 'update_pic', :as => 'update_pic'

  get 'page_content/:content_page_id/move_up/:id', :controller => 'page_blocks', :action => 'move_up', :as => 'move_up_page_blocks'
  get 'page_content/:content_page_id/move_down/:id', :controller => 'page_blocks', :action => 'move_down', :as => 'move_down_page_blocks'


  resources :statute_types do
    resources :statutes
    resources :text_entries
  end

  match 'jurisdictions/geocode', :controller => 'jurisdictions', :action => 'geocode'
  resources :jurisdictions


  get "home/index"

  devise_for :users

  root :to => 'home#index'

end

app/models/page_block.rb
class PageBlock < ActiveRecord::Base
  attr_accessible :content_page_id, :block_type_id, :order_count

  belongs_to :content_pages
  belongs_to :block_type

  # def hasPicture
  #   puts 'self.id = ' + self.id.inspect
  # 	pics = Picture.where({:block_person_id => self.id}).all
  #   puts 'pics = ' + pics.inspect
  # 	if pics.nil?
  # 		return false
  # 	else
  #     return true
  #   end
  # end

  # def picture
  # 	if self.hasPicture
  # 		return Picture.where({:block_person_id => self.id}).first
  # 	end
  # end

  def last
    blocks = PageBlock.where(:content_page_id => self.content_page_id).order('order_count')
    return blocks.last.order_count
  end

end

app/controllers/page_blocks_controller.rb
class PageBlocksController < ProtectedApplicationController

	def new
		@block = PageBlock.new
		@block.content_page_id = params[:content_page_id]
		pageBlocks = PageBlock.where({:content_page_id => params[:content_page_id]}).order(:order_count)
		puts "pageBlocks = " + pageBlocks.inspect
		if pageBlocks.any?
			lastNumber = pageBlocks.last[:order_count].to_i
			@block.order_count = lastNumber + 1
		else
			@block.order_count = 1
		end
		puts 'block.order_count = ' + @block.order_count.inspect

		@blockTypes = BlockType.all.map {|block_type| [block_type.name, block_type.id]}
		puts 'blockTypes = ' + @blockTypes.inspect
		@form_action = 'create'
		puts 'form_action = ' + @form_action.inspect

		@editingBlock = true
		respond_to do |format|
	      #format.html # new.html.erb
	      format.js { render :new_block }
	      format.json { render json: @block }
	    end
	end

	def edit
		puts 'edit block params = ' + params.inspect
		puts 'params[:id] = ' + params[:id].inspect
		@myBlock = PageBlock.find(params[:id])
		@page = ContentPage.find(@myBlock.content_page_id)
		puts 'block = ' + @myBlock.inspect
		puts 'page = ' + @page.inspect

		@editingBlock = true

		respond_to do |format|
			if @myBlock.block_type_id == 1
				@blockPerson = BlockPerson.find(@myBlock.id)
				puts 'blockPerson = ' + @blockPerson.inspect
				@path = update_block_person_path(@blockPerson.content_page_id, @blockPerson)
				format.js { render :edit_block_person }
	      		format.json { render json: @blockPerson }
			else
				@blockText = BlockPlainText.find(@myBlock.id)
				puts 'blockText = ' + @blockText.inspect
				@path = update_block_plain_text_path(@blockText)
				format.js { render :edit_block_text }
	      		format.json { render json: @blockText }
			end
	    end
	end

	def destroy
		puts 'destroy_page_block params = ' + params.inspect
		@block = PageBlock.find(params[:id])
		puts 'block = ' + @block.inspect
		page_id = @block.content_page_id
		puts 'page_id = ' + page_id.inspect
		order_number = @block.order_count
		puts 'order number = ' + order_number.inspect
		all_blocks = PageBlock.where({:content_page_id => page_id}).order('order_count')
		puts 'all_blocks before each = ' + all_blocks.inspect
		#change order of blocks so theydon't include block about to be deleted
		all_blocks.each do |b|
			if b.order_count > order_number
				b.order_count = b.order_count - 1
				b.save
			end
		end
		puts 'all_blocks after each = ' + all_blocks.inspect
		@block.destroy

		respond_to do |format|
	      format.html { redirect_to show_content_pages_path(page_id) }
	      format.json { head :no_content }
	    end
	end

	def create
		puts 'params = ' + params.inspect
		blockInfo = params[:page_block]
		@block = PageBlock.new(blockInfo)
		@page = ContentPage.where(@block.content_page_id).first

		respond_to do |format|
			puts 'format = ' + format.inspect
	      	if @block.block_type_id == 1
	      		@blockPerson = BlockPerson.new

	      		#set hidden values
	      		@blockPerson.order_count = @block.order_count
	      		@blockPerson.content_page_id = @block.content_page_id
	      		@blockPerson.block_type_id = @block.block_type_id
	      		puts 'blockPerson = ' + @blockPerson.inspect
	      		#set path
	      		@path = create_block_person_path
	      		#render
	        	format.js { render :new_person }
	      		format.json { render json: @blockPerson }
	        elsif @block.block_type_id == 2
	        	@blockText = BlockPlainText.new

	        	#set hidden values
	      		@blockText.order_count = @block.order_count
	      		@blockText.content_page_id = @block.content_page_id
	      		@blockText.block_type_id = @block.block_type_id
	      		puts 'blockPerson = ' + @blockText.inspect
	      		#set path
	      		@path = create_block_text_path
	      		#render
	        	format.js { render :new_text }
	      		format.json { render json: @blockText }
	        end
	    end
	end

	def create_block_person
		puts 'create_block_person params = ' + params.inspect
		@blockPerson = BlockPerson.new(params[:block_person])
		# url = @blockPerson.get_picture_url
		# uriRequest = URI(request.url) + url
		# puts 'uriReq = '+ uriRequest.inspect
		# @blockPerson.picture_url = uriRequest.to_s
		puts '@blockPerson = ' + @blockPerson.inspect
		pageId = @blockPerson[:content_page_id]
		@page = ContentPage.find(pageId)
		puts 'page = ' + @page.inspect

		respond_to do |format|
	      if @blockPerson.save
	      	url = @blockPerson.get_picture_url
			uriRequest = URI(request.url) + url
			puts 'uriReq = '+ uriRequest.inspect
			@blockPerson.picture_url = uriRequest.to_s
			if @blockPerson.save
		      	@editingBlock = false
		        format.html { redirect_to show_content_pages_path(@page.id), notice: 'Person was successfully created.' }
		        format.json { render json: @blockPerson, status: :created, location: @blockPerson }
		    else
		    	format.html { render action: "new_block_person", alert: 'Unable to create picture url successfully.'}
	        	format.json { render json: @blockPerson.errors, status: :unprocessable_entity }
	        end
	      else
	        format.html { render action: "new_block_person", alert: 'Unable to create Person.' }
	        format.json { render json: @blockPerson.errors, status: :unprocessable_entity }
	      end
	    end

	end

	def create_block_text
		puts 'create_block_text params = ' + params.inspect
		@blockText = BlockPlainText.new(params[:block_plain_text])
		puts '@blockText = ' + @blockText.inspect
		@blockText.cleanup
		pageId = @blockText[:content_page_id].inspect
		@page = ContentPage.find(pageId)
		puts 'page = ' + @page.inspect

		respond_to do |format|
	      if @blockText.save
	      	@editingBlock = false
	        format.html { redirect_to show_content_pages_path(@page.id), notice: 'Text Block was successfully created.' }
	        format.json { render json: @blockPerson, status: :created, location: @blockText }
	      else
	        format.html { render action: "new_block_plain_text" }
	        format.json { render json: @blockText.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def update_block_person
		puts 'update block person params = ' + params.inspect
		@pic = nil
		@blockPerson = BlockPerson.find(params[:id])
		@page_id = @blockPerson.content_page_id

		respond_to do |format|
			if @blockPerson.update_attributes(params[:block_person])
				url = @blockPerson.get_picture_url
				uriRequest = URI(request.url) + url
				puts 'uriReq = '+ uriRequest.inspect
				@blockPerson.picture_url = uriRequest.to_s
				#@blockPerson.picture_url = URI.join(request.url, url)
				puts 'blockPerson after get_picture_url = ' + @blockPerson.inspect
				if @blockPerson.save
					@editingBlock = false
					format.html { redirect_to show_content_pages_path(@page_id), notice: 'Block was successfully updated.' }
		        	format.json { head :no_content }
		        else
		        	format.html { render edit_page_blocks_path(@blockPerson.id), alert: 'Unable to save picture url successfully.'}
	        		format.json { render json: @blockPerson.errors, status: :unprocessable_entity }
	        	end
			else
				format.html { render edit_page_blocks_path(@blockPerson.id), alert: 'Unable to update Block successfully.'}
	        	format.json { render json: @blockPerson.errors, status: :unprocessable_entity }
			end
		end
	end

	def update_block_plain_text
		puts 'upddate block text params = ' + params.inspect
		@blockText = BlockPlainText.find(params[:id])
		@page_id = @blockText.content_page_id

		respond_to do |format|
			if @blockText.update_attributes(params[:block_plain_text])
				@blockText.cleanup
				if @blockText.save
					@editingBlock = false
					format.html { redirect_to show_content_pages_path(@page_id), notice: 'Block was successfully updated.' }
					format.json { head :no_content }
				else
					format.html { render edit_page_blocks_path(@blockText.id), alert: 'Unable to update Block-cleanup successfully.' }
					format.json { render json: @blockText.errors, status: :unprocessable_entity }
				end
			else
				format.html { render edit_page_blocks_path(@blockText.id), alert: 'Unable to update Block successfully.' }
				format.json { render json: @blockText.errors, status: :unprocessable_entity }
			end
		end
	end

	def create_pic
		puts 'create_photo params = ' + params.inspect
		@blockPerson_id = params[:id]
		puts 'blockPerson_id = ' + @blockPerson_id.inspect
		#@pic.destroy
		@blockPerson = BlockPerson.find(@blockPerson_id)
		@editingBlock = true

		respond_to do |format|
			#@path = update_pic_path(@blockPerson.content_page_id,@blockPerson, :format => :js)
			@path = update_pic_path(@blockPerson.content_page_id,@blockPerson)
			puts 'creat_pic-> path = ' + @path.inspect
			format.js { render :create_pic }
      		format.json { render json: @blockPerson }
      	end
	end

	def update_pic
		puts 'update_pic params = ' + params.inspect
		pictureParams = (params[:block_person])[:picture_attributes]
		puts 'pictureParams = ' + pictureParams.inspect
		block_id = params[:id]
		puts 'block_id = ' + block_id.inspect
		Picture.where('block_person_id = ? AND id <> ?', block_id, pictureParams[:id]).delete_all
		@blockPerson = BlockPerson.find(block_id)
		puts 'blockPerson = ' + @blockPerson.inspect
		@page = ContentPage.find(params[:content_page_id])
		puts 'page = ' + @page.inspect

		respond_to do |format|
			if @blockPerson.update_attributes(params[:block_person])
        url = @blockPerson.get_picture_url
        uriRequest = URI(request.url) + url
        puts 'uriReq = '+ uriRequest.inspect
        @blockPerson.picture_url = uriRequest.to_s
        if @blockPerson.save
  				@editingBlock = false
  				# @path = update_block_person_path(@blockPerson)
  				# format.js { render :edit_block_person }
  	   			# format.json { render json: @blockPerson }
  				format.html { redirect_to show_content_pages_path(@page.id), notice: 'Picture and Person was successfully updated.' }
  				format.json { render json: @page }

app/views/page_blocks/_block_person_form.html.erb
<%= form_for(setup_block_person(@blockPerson), :url => @path, :html => { :multipart => true, :class => 'form-horizontal' } ) do |f| %>
  <% if @blockPerson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blockPerson.errors.count, "error") %> prohibited this Person from being saved:</h2>

      <ul>
      <% @blockPerson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <div class='col-xs-12' style = "border:1px solid #033C73; margin-top:10px; margin-bottom:10px;">
    <%= link_to show_content_pages_path(@blockPerson.content_page_id), :class => 'btn btn-danger', :style => 'float:right;margin-top: 10px;' do %>
      <i class="fa fa-times-circle fa-lg"></i>
    <% end %>

    <h2> <% if !@blockPerson.id.nil? %> Updating Person with ID: <%= @blockPerson.id %> <% else %> New Person<% end %> </h2>
    <p> Page: <%= @page.name %>, <%= @blockPerson.content_page_id %></p>

    <div class="form-group">
      <%= f.label :name, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :title, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :phone, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label 'Page', :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
      <%= f.text_field :url, :class => 'form-control' %>
      </div>
    </div>

    <div class ='form-group'>
      <%= f.fields_for :picture do |p| %>
        <%= p.label :photo, :class => 'col-lg-2 control-label' %>
        <div class = 'col-lg-10'>
          <% if @blockPerson.hasPicture %>
            <p><%= @blockPerson.get_picture.photo_file_name %> </p>
            <p><%= image_tag @blockPerson.picture.photo.url(:thumb) %></p>
            <p><%= link_to 'Update New photo', create_pic_path(@page.id, @blockPerson.id), :remote => true, :class => 'btn btn-warning' %></p>
          <% else %>
            <%= p.file_field :photo %>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= f.hidden_field :block_type_id, :value => @blockPerson.block_type_id %>
    <%= f.hidden_field :content_page_id, :value => @blockPerson.content_page_id %>
    <%= f.hidden_field :order_count, :value => @blockPerson.order_count %>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2" style="margin-top: 50px;">
        <%if @blockPerson.id.nil? %>
          <%= f.submit 'Submit New Person', :class => "btn btn-primary" %>
        <% else %>
          <%= f.submit 'Update Person', :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  </fieldset>
<% end %>

app/views/page_blocks/_block_text_form.html.erb
<%= form_for([@blockText], :url => @path, :html => { :class => 'form-horizontal' } ) do |f| %>
  <% if @blockText.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blockText.errors.count, "error") %> prohibited this Person from being saved:</h2>

      <ul>
      <% @blockText.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <div class='col-xs-12' style = "border:1px solid #033C73; margin-top:10px; margin-bottom:10px;">
	<%= link_to show_content_pages_path(@blockText.content_page_id), :class => 'btn btn-danger', :style => 'float:right;margin-top: 10px;' do %>
      <i class="fa fa-times-circle fa-lg"></i>
    <% end %>

    <h2> <% if !@blockText.id.nil? %> Updating Text with ID: <%= @blockText.id %><% else %> New Text Form<% end %> </h2>
    <p> Page: <%= @page.name %>, <%= @blockText.content_page_id %> </p>
    <p class="alert alert-info"> Note: In order to add a Phone Number or Email, you must click on the "add link" button. <br> Write the Phone Number or Email however you wish people to see it in the "Text to display" field, and in the URL field, please do the following: <br>
      &emsp;For Phone Numbers: tel:+phone-number     Example: tel:+1-800-555-5555 <br>&emsp; (Uses dashes to separate the numbers.)<br>
      &emsp;For Emails: mailto:email-address         Example: mailto:example@myDomain.com
    </p>

    <div class="form-group">
      <%= f.label :content_value, :class => 'col-xs-12 control-label', :style => 'float:left;' %>
      <div class="col-xs-12">
        <%= f.text_area :content_value, :class => 'form-control tinymce' %>
      </div>
    </div>

    <%= f.hidden_field :block_type_id, :value => @blockText.block_type_id %>
    <%= f.hidden_field :content_page_id, :value => @blockText.content_page_id %>
    <%= f.hidden_field :order_count, :value => @blockText.order_count %>

    <div class="form-group">
      <div class="col-lg-4 col-lg-offset-4" style="margin-top: 50px;">
        <% if @blockText.id.nil? %>
          <%= f.submit 'Submit New Text', :class => "btn btn-primary" %>
        <% else %>
          <%= f.submit 'Update Text', :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  </fieldset>
<% end %>

<%= tinymce %>

app/views/page_blocks/_form.html.erb
<%= form_for([@block], :url => {:action => @form_action}, :remote => true, :html => { :class => 'form-horizontal' } ) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class='col-xs-12 col-lg-10 col-lg-offset-1' style = "border:1px solid #033C73; margin-top:10px;">
      <%= link_to show_content_pages_path(@block.content_page_id), :class => 'btn btn-danger', :style => 'float:right;margin-top: 10px;' do %>
        <i class="fa fa-times-circle fa-lg"></i>
      <% end %>

    	<h2> New Block </h2>
      

      <%= f.label (:block_type_id), :class => 'control-label col-xs-3' %>
      <div class='col-xs-9' id="blockTypeSelect">
        <%= f.select :block_type_id, @blockTypes do %>
          <% @blockTypes.each do |type| %>
            <%= content_tag(:option, type.first, value: type.last) %>
          <% end %>
        <% end %>
      </div>

      <%= f.hidden_field :content_page_id, :value => @block.content_page_id %>
      <%= f.hidden_field :order_count, :value => @block.order_count %>

      <div class="form-group">
        <div class="col-lg-4 col-lg-offset-4" style="margin-top: 50px;" style="text-align:center">
          <%= f.submit 'Next', :class => "btn btn-success" %>
        </div>
      </div>
    </div>
  </fieldset>

<% end %>

app/views/page_blocks/_new_picture_form.html.erb
<%= form_for(setup_block_person(@blockPerson), :url => @path, :remote => true, :html => { :multipart => true, :class => 'form-horizontal' } ) do |f| %>
  <% if @blockPerson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blockPerson.errors.count, "error") %> prohibited this Person from being saved:</h2>

      <ul>
      <% @blockPerson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <div class='col-xs-12' style = "border:1px solid #033C73; margin-top:10px; margin-bottom:10px;">
    <%= link_to show_content_pages_path(@blockPerson.content_page_id), :class => 'btn btn-danger', :style => 'float:right;margin-top: 10px;' do %>
      <i class="fa fa-times-circle fa-lg"></i>
    <% end %>

    <h2> Upload New Photo </h2>

    <div class ='form-group'>
      <%= f.fields_for :picture do |p| %>
        <%= p.label :photo, :class => 'col-lg-2 control-label' %>
        <div class = 'col-lg-10'>
            <%= p.file_field :photo %>
        </div>

        <%= p.hidden_field :block_person_id, :value => @blockPerson.id %>
      <% end %>
    </div>

    

    <div class="form-group">
      <div class="col-lg-4 col-lg-offset-4" style="margin-top: 50px;" style="text-align:center">
        <%= f.submit 'Next', :class => "btn btn-success" %>
      </div>
    </div>

  </div>
  </fieldset>
<% end %>

app/views/page_blocks/create_pic.js.erb
$("#showBlock<%= @blockPerson_id %>").html("<%=escape_javascript(render :partial=>'page_blocks/new_picture_form',locals: { blockPerson: @blockPerson} )%>");

app/views/page_blocks/edit.html.erb
<% render 'form' %>

app/views/page_blocks/edit_block_person.js.erb
$("#showBlock<%= @blockPerson.id %>").html("<%=escape_javascript(render :partial=>'page_blocks/block_person_form',locals: { blockPerson: @blockPerson, page: @page} )%>");

app/views/page_blocks/new.html.erb
<% render 'form' %>

app/views/page_blocks/new_block.js.erb
console.log('made it to new block');
$("#newPageBlock").html("<%=escape_javascript(render :partial=>'page_blocks/form',locals: { block: @block} )%>");

app/views/page_blocks/new_person.js.erb
$("#newPageBlock").html("<%=escape_javascript(render :partial=>'page_blocks/block_person_form',locals: { blockPerson: @blockPerson, pic: @pic, page: @page} )%>");

app/views/page_blocks/new_text.js.erb
$("#newPageBlock").html("<%=escape_javascript(render :partial=>'page_blocks/block_text_form',locals: { blockText: @blockText, page: @page} )%>");

app/views/page_blocks/show_block_person.html.erb
<div class="col-xs-12 col-lg-10 col-lg-offset-1" style="border:1px solid #033C73;background-color:#EAF2FA;color:#033C73; padding:5px;">
	<div class='col-xs-3' style="float:right;">
		<% if @blockPerson.order_count > 1 %>
			<%= link_to move_up_page_blocks_path(@blockPerson.id), :class => 'col-xs-12 btn btn-info', :style => 'float:right;margin-top:5px;' do %>
				<i class="fa fa-sort-asc"></i> Move Up
			<% end %>
		<% end %>
		<% if @blockPerson.order_count < @blockPerson.last %>
			<%= link_to move_down_page_blocks_path(@blockPerson.id), :class => 'col-xs-12 btn btn-info', :style => 'float:right;margin-top:5px;' do %>
				<i class="fa fa-sort-desc"></i> Move Down
			<% end %>
		<% end %>
	</div>
	<div class="col-xs-9" >
		<h2 style="margin-top:5px;"> <%= @blockPerson.block_type.name %></h2>
		<div class="col-xs-12 col-lg-5" style="float:right; padding-bottom: 20px;">
			<% if @blockPerson.hasPicture %>
				<%= image_tag @blockPerson.get_picture.photo.url(:small) %>
			<% else %>
				No Picture Added
			<% end %>
		</div>
		<div class="col-xs-12 col-lg-7" style="float:left;">
			<p><strong>Name:</strong> <%= @blockPerson.name %> </p>
			<p><strong>Title:</strong> <%= @blockPerson.title %> </p>
			<p><strong>Email:</strong> <%= @blockPerson.email %></p>
			<p><strong>Phone:</strong> <%= @blockPerson.phone %></p>
			<p><strong>Page:</strong> <a href="<%= @blockPerson.url %>" style="word-wrap:break-word;"><%= @blockPerson.url %></a></p>
		</div>
	</div>
	
	<div class="col-xs-12 col-lg-12"><p></p></div>
	<div class="col-xs-12 col-lg-12" style="margin-top:20px;float:left;">
		<%= link_to 'Edit Person', edit_page_blocks_path(@blockPerson.id), :remote => true, :class => 'btn btn-success' %>
		<%= link_to 'Delete Person', destroy_page_blocks_path(@blockPerson.content_page_id, @blockPerson.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
	</div>
</div>

app/views/page_blocks/show_block_text.html.erb
<div class="col-xs-12 col-lg-10 col-lg-offset-1" style="border:1px solid #033C73;background-color:#EAF2FA;color:#033C73; padding:5px;">
	<div class='col-xs-3' style="float:right;">
	<% if @blockText.order_count > 1 %>
		<%= link_to move_up_page_blocks_path(@blockText.id), :class => 'col-xs-12 btn btn-info', :style => 'float:right;margin-top:5px;' do %>
			<i class="fa fa-sort-asc"></i> Move Up
		<% end %>
	<% end %>
	<% if @blockText.order_count < @blockText.last %>
		<%= link_to move_down_page_blocks_path(@blockText.id), :class => 'col-xs-12 btn btn-info', :style => 'float:right;margin-top:5px;' do %>
			<i class="fa fa-sort-desc"></i> Move Down
		<% end %>
	<% end %>
	</div>
	<h2 style="margin-top:5px;"> <%= @blockText.block_type.name %></h2>

	<div class="col-xs-12" style="padding:0px 30px;">
		<%= @blockText.content_value.html_safe %>
	</div>

	<div class="col-xs-12">
		<%= link_to 'Edit Text', edit_page_blocks_path(@blockText.id), :remote => true, :class => 'btn btn-success' %>
		<%= link_to 'Delete Text', destroy_page_blocks_path(@blockText.content_page_id, @blockText.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
	</div>
</div>

app/views/page_blocks/show_content_pages.js.erb
pathname = 'localhost:3000/content_pages/show/<%= @page.id %>'
window.location.replace(window.location.pathname);