config/routes.rb
FoxAppsRails::Application.routes.draw do

  resources :user_management

  match 'API10/jurisdiction_list', :controller => 'api10', :action => 'jurisdiction_list'
  match 'API10/jurisdiction_statute/:id', :controller => 'api10', :action => 'jurisdiction_statute'
  match 'API10/jurisdiction_statutes/:id', :controller => 'api10', :action => 'jurisdiction_statutes'
  match 'API10/content_pages/:name/get_all_page_blocks', :controller => 'api10', :action => 'get_all_page_blocks'

  get 'content_pages/', :controller => 'content_pages', :action => 'index'
  get 'content_pages/new', :controller =>'content_pages', :action => 'new'
  get 'content_pages/show/:id', :controller => 'content_pages', :action => 'show', :as => 'show_content_pages'
  get 'content_pages/edit/:id', :controller => 'content_pages', :action => 'edit', :as => 'edit_content_pages'
  post 'content_pages/create/', :controller => 'content_pages', :action => 'create_page', :as => 'create_content_pages'
  put 'content_pages/update/:id', :controller => 'content_pages', :action => 'update', :as => 'update_content_pages'
  delete 'content_pages/destroy/:id', :controller => 'content_pages', :action => 'destroy', :as => 'destroy_content_pages'

  get 'page_blocks/show/:id', :controller => 'page_blocks', :action => 'show', :as => 'show_page_blocks'
  get 'content_pages/:content_page_id/page_blocks/new', :controller => 'page_blocks', :action => 'new', :as => 'new_page_blocks'
  get 'page_blocks/edit/:id', :controller => 'page_blocks', :action => 'edit', :as => 'edit_page_blocks'
  post 'page_blocks/:content_page_id', :controller => 'page_blocks', :action => 'create', :as => 'create_page_blocks'
  delete 'page_content/show/:content_page_id/:id', :controller => 'page_blocks', :action => 'destroy', :as => 'destroy_page_blocks'

  get 'page_content/:content_page_id/page_block/new_block_person/', :controller => 'page_blocks', :action => 'new_block_person', :as => 'new_block_person'
  post 'content_pages/show/create_block_person', :controller => 'page_blocks', :action => 'create_block_person', :as => 'create_block_person'
  put 'content_pages/:content_page_id/page_block/update_block_person/:id', :controller => 'page_blocks', :action => 'update_block_person', :as => 'update_block_person'
  get 'page_content/:content_page_id/page_block/new_plain_text/', :controller => 'page_blocks', :action => 'new_block_plain_text', :as => 'new_block_plain_text'
  post 'content_pages/show/create_block_text', :controller => 'page_blocks', :action => 'create_block_text', :as => 'create_block_text'
  put 'content_pages/show/update_block_plain_text/:id', :controller => 'page_blocks', :action => 'update_block_plain_text', :as => 'update_block_plain_text'
  get 'content_pages/:content_page_id/page_block/:id/create_pic', :controller => 'page_blocks', :action => 'create_pic', :as => 'create_pic'
  put 'content_page/:content_page_id/page_block/:id/update_pic', :controller => 'page_blocks', :action => 'update_pic', :as => 'update_pic'

  get 'page_content/:content_page_id/move_up/:id', :controller => 'page_blocks', :action => 'move_up', :as => 'move_up_page_blocks'
  get 'page_content/:content_page_id/move_down/:id', :controller => 'page_blocks', :action => 'move_down', :as => 'move_down_page_blocks'


  resources :statute_types do
    resources :statutes
    resources :text_entries
  end

  match 'jurisdictions/geocode', :controller => 'jurisdictions', :action => 'geocode'
  resources :jurisdictions


  get "home/index"

  devise_for :users

  root :to => 'home#index'

end

app/models/jurisdiction.rb
class Jurisdiction < ActiveRecord::Base
  acts_as_mappable
  attr_accessible :name, :lat, :lng, :zip, :short_name
  has_many :statutes
  before_validation :geocode_address

  def geocode_address
  	!zip ? return : nil
    #geo = Geokit::Geocoders::MultiGeocoder.geocode(zip)
    begin
      geo = Geokit::Geocoders::GoogleGeocoder3.geocode(zip)
      puts zip
      puts geo
      self.lat, self.lng = geo.lat,geo.lng
    rescue Geokit::Geocoders::GeocodeError
      self.lat, self.lng = nil,nil
    end
  end
end

app/controllers/jurisdictions_controller.rb
class JurisdictionsController < ProtectedApplicationController
  
  # GET /jurisdictions
  # GET /jurisdictions.json
  def index
    @jurisdictions = Jurisdiction.order('name')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jurisdictions }
    end
  end

  # GET /jurisdictions/1
  # GET /jurisdictions/1.json
  def show
    @jurisdiction = Jurisdiction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jurisdiction }
    end
  end

  # GET /jurisdictions/new
  # GET /jurisdictions/new.json
  def new
    @jurisdiction = Jurisdiction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jurisdiction }
    end
  end

  # GET /jurisdictions/1/edit
  def edit
    @jurisdiction = Jurisdiction.find(params[:id])
  end

  # POST /jurisdictions
  # POST /jurisdictions.json
  def create
    @jurisdiction = Jurisdiction.new(params[:jurisdiction])

    respond_to do |format|
      if @jurisdiction.save
        format.html { redirect_to jurisdictions_url, notice: 'Jurisdiction was successfully created.' }
        format.json { render json: @jurisdiction, status: :created, location: @jurisdiction }
      else
        format.html { render action: "new" }
        format.json { render json: @jurisdiction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jurisdictions/1
  # PUT /jurisdictions/1.json
  def update
    @jurisdiction = Jurisdiction.find(params[:id])

    respond_to do |format|
      if @jurisdiction.update_attributes(params[:jurisdiction])
        format.html { redirect_to jurisdictions_url, notice: 'Jurisdiction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jurisdiction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jurisdictions/1
  # DELETE /jurisdictions/1.json
  def destroy
    @jurisdiction = Jurisdiction.find(params[:id])
    @jurisdiction.destroy

    respond_to do |format|
      format.html { redirect_to jurisdictions_url }
      format.json { head :no_content }
    end
  end

  def geocode
    Jurisdiction.all.each do |jurisdiction|
      jurisdiction.save
    end
    render :text => 'done'
  end
end

app/helpers/jurisdictions_helper.rb
module JurisdictionsHelper
end

app/views/jurisdictions/_form.html.erb
<%= form_for(@jurisdiction, :html => { :class => 'form-horizontal' } ) do |f| %>
  <% if @jurisdiction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jurisdiction.errors.count, "error") %> prohibited this jurisdiction from being saved:</h2>

      <ul>
      <% @jurisdiction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <fieldset>
    <legend>Jusisdiction</legend>
    <div class="form-group">
      <%= f.label :name, :class => 'col-lg-2 control-label' %>
      <div class="col-xs-4">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :short_name, :class => 'col-lg-2 control-label' %>
      <div class="col-xs-2">
        <%= f.text_field :short_name, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :zip, :class => 'col-lg-2 control-label' %>
      <div class="col-xs-3">
        <%= f.text_field :zip, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit 'Submit', :class => "btn btn-primary" %>
      </div>
    </div>
  </fieldset>

<% end %>

app/views/jurisdictions/edit.html.erb
<div class="well">
<%= render 'form' %>
</div>

app/views/jurisdictions/index.html.erb
<h2>Jurisdictions</h2>

<table class="table table-striped table-bordered table-hover">
  <tr>
    <th>Name</th>
    <th>Short Name</th>
    <th>Capitol Zip</th>
    <th></th>
  </tr>

<% @jurisdictions.each do |jurisdiction| %>
  <tr>
    <td><%= jurisdiction.name %></td>
    <td><%= jurisdiction.short_name %></td>
    <td><%= jurisdiction.zip %></td>
    <td><%= link_to 'Edit', edit_jurisdiction_path(jurisdiction), :class => "btn btn-primary btn-xs" %>
    <%= link_to 'Destroy', jurisdiction, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Jurisdiction', new_jurisdiction_path, :class => "btn btn-success" %>

app/views/jurisdictions/new.html.erb
<div class="well">
<%= render 'form' %>
</div>

app/views/jurisdictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @jurisdiction.name %>
</p>


<%= link_to 'Edit', edit_jurisdiction_path(@jurisdiction) %> |
<%= link_to 'Back', jurisdictions_path %>