config/routes.rb
FoxAppsRails::Application.routes.draw do

  resources :user_management

  match 'API10/jurisdiction_list', :controller => 'api10', :action => 'jurisdiction_list'
  match 'API10/jurisdiction_statute/:id', :controller => 'api10', :action => 'jurisdiction_statute'
  match 'API10/jurisdiction_statutes/:id', :controller => 'api10', :action => 'jurisdiction_statutes'
  match 'API10/content_pages/:name/get_all_page_blocks', :controller => 'api10', :action => 'get_all_page_blocks'

  get 'content_pages/', :controller => 'content_pages', :action => 'index'
  get 'content_pages/new', :controller =>'content_pages', :action => 'new'
  get 'content_pages/show/:id', :controller => 'content_pages', :action => 'show', :as => 'show_content_pages'
  get 'content_pages/edit/:id', :controller => 'content_pages', :action => 'edit', :as => 'edit_content_pages'
  post 'content_pages/create/', :controller => 'content_pages', :action => 'create_page', :as => 'create_content_pages'
  put 'content_pages/update/:id', :controller => 'content_pages', :action => 'update', :as => 'update_content_pages'
  delete 'content_pages/destroy/:id', :controller => 'content_pages', :action => 'destroy', :as => 'destroy_content_pages'

  get 'page_blocks/show/:id', :controller => 'page_blocks', :action => 'show', :as => 'show_page_blocks'
  get 'content_pages/:content_page_id/page_blocks/new', :controller => 'page_blocks', :action => 'new', :as => 'new_page_blocks'
  get 'page_blocks/edit/:id', :controller => 'page_blocks', :action => 'edit', :as => 'edit_page_blocks'
  post 'page_blocks/:content_page_id', :controller => 'page_blocks', :action => 'create', :as => 'create_page_blocks'
  delete 'page_content/show/:content_page_id/:id', :controller => 'page_blocks', :action => 'destroy', :as => 'destroy_page_blocks'

  get 'page_content/:content_page_id/page_block/new_block_person/', :controller => 'page_blocks', :action => 'new_block_person', :as => 'new_block_person'
  post 'content_pages/show/create_block_person', :controller => 'page_blocks', :action => 'create_block_person', :as => 'create_block_person'
  put 'content_pages/:content_page_id/page_block/update_block_person/:id', :controller => 'page_blocks', :action => 'update_block_person', :as => 'update_block_person'
  get 'page_content/:content_page_id/page_block/new_plain_text/', :controller => 'page_blocks', :action => 'new_block_plain_text', :as => 'new_block_plain_text'
  post 'content_pages/show/create_block_text', :controller => 'page_blocks', :action => 'create_block_text', :as => 'create_block_text'
  put 'content_pages/show/update_block_plain_text/:id', :controller => 'page_blocks', :action => 'update_block_plain_text', :as => 'update_block_plain_text'
  get 'content_pages/:content_page_id/page_block/:id/create_pic', :controller => 'page_blocks', :action => 'create_pic', :as => 'create_pic'
  put 'content_page/:content_page_id/page_block/:id/update_pic', :controller => 'page_blocks', :action => 'update_pic', :as => 'update_pic'

  get 'page_content/:content_page_id/move_up/:id', :controller => 'page_blocks', :action => 'move_up', :as => 'move_up_page_blocks'
  get 'page_content/:content_page_id/move_down/:id', :controller => 'page_blocks', :action => 'move_down', :as => 'move_down_page_blocks'


  resources :statute_types do
    resources :statutes
    resources :text_entries
  end

  match 'jurisdictions/geocode', :controller => 'jurisdictions', :action => 'geocode'
  resources :jurisdictions


  get "home/index"

  devise_for :users

  root :to => 'home#index'

end

app/controllers/statute_types_controller.rb
class StatuteTypesController < ProtectedApplicationController
 
  def is_numeric?(obj) 
     obj.to_s.match(/\A[+-]?\d+?(\.\d+)?\Z/) == nil ? false : true
  end
  # GET /statute_types
  # GET /statute_types.json
  def index
    @statute_types = StatuteType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statute_types }
    end
  end

  # GET /statute_types/1
  # GET /statute_types/1.json
  def show
    @id = params[:id]
    if is_numeric? @id
      @statute_type = StatuteType.find(params[:id])
    else
      @statute_type = StatuteType.find_by_name_slug(params[:id])
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @statute_type }
    end
  end

  # GET /statute_types/new
  # GET /statute_types/new.json
  def new
    @statute_type = StatuteType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @statute_type }
    end
  end

  # GET /statute_types/1/edit
  def edit
    @statute_type = StatuteType.find(params[:id])
  end

  # POST /statute_types
  # POST /statute_types.json
  def create
    @statute_type = StatuteType.new(params[:statute_type])

    respond_to do |format|
      if @statute_type.save
        format.html { redirect_to @statute_type, notice: 'Statute type was successfully created.' }
        format.json { render json: @statute_type, status: :created, location: @statute_type }
      else
        format.html { render action: "new" }
        format.json { render json: @statute_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statute_types/1
  # PUT /statute_types/1.json
  def update
    @statute_type = StatuteType.find(params[:id])

    respond_to do |format|
      if @statute_type.update_attributes(params[:statute_type])
        format.html { redirect_to @statute_type, notice: 'Statute type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @statute_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statute_types/1
  # DELETE /statute_types/1.json
  def destroy
    @statute_type = StatuteType.find(params[:id])
    @statute_type.destroy

    respond_to do |format|
      format.html { redirect_to statute_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statute_types_helper.rb
module StatuteTypesHelper
end

app/views/statute_types/_form.html.erb
<%= form_for(@statute_type) do |f| %>
  <% if @statute_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statute_type.errors.count, "error") %> prohibited this statute_type from being saved:</h2>

      <ul>
      <% @statute_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statute_types/edit.html.erb
<h1>Editing statute_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @statute_type %> |
<%= link_to 'Back', statute_types_path %>

app/views/statute_types/index.html.erb
<h1>Listing statute_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statute_types.each do |statute_type| %>
  <tr>
    <td><%= statute_type.name %></td>
    <td><%= link_to 'Show', statute_type %></td>
    <td><%= link_to 'Edit', edit_statute_type_path(statute_type) %></td>
    <td><%= link_to 'Destroy', statute_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Statute type', new_statute_type_path %>

app/views/statute_types/new.html.erb
<h1>New statute_type</h1>

<%= render 'form' %>

app/views/statute_types/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @statute_type.name  %></h3>

<ul class="nav nav-tabs" style="margin-bottom: 10px;">
  <li class="active"><a href="#statutes" data-toggle="tab">Statutes</a></li>
  <li><a href="#text" data-toggle="tab">Text</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="statutes">
    <table class="table table-striped table-bordered table-hover">
      <tr>
        <th>Name</th>
        <th>Jurisdiction</th>
        <th></th>
      </tr>

    <% @statute_type.statutes.each do |statute| %>
      <tr>
        <td><%= statute.name %></td>
        <td><%= statute.jurisdiction.name if statute.jurisdiction %></td>
        <td><%= link_to 'Edit', edit_statute_type_statute_path(@statute_type, statute), :class => "btn btn-primary btn-xs" %>
        <%= link_to 'Destroy', statute_type_statute_path(@statute_type, statute), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %></td>
      </tr>

    <% end %>
    </table>
    <%= link_to 'Add Statute', new_statute_type_statute_path(@statute_type), :class => 'btn btn-success' %>
  </div>
  <div class="tab-pane" id="text">
        <table class="table table-striped table-bordered table-hover">
      <tr>
        <th>Text</th>
        <th>Jurisdiction</th>
        <th></th>
      </tr>
      <% @statute_type.text_entries.each do |text_entry| %>
        <tr>
          <td><%= raw text_entry.shorten_text_value%></td>
          <td><%= text_entry.jurisdiction.name if text_entry.jurisdiction %></td>
          <td><%= link_to 'Edit', edit_statute_type_text_entry_path(@statute_type, text_entry), :class => "btn btn-primary btn-xs" %>
          <%= link_to 'Destroy', statute_type_text_entry_path(@statute_type, text_entry), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %></td>
        </tr>
      <% end %>
    </table>
    <%= link_to 'Add Jurisdiction Text', new_statute_type_text_entry_path(@statute_type), :class => 'btn btn-success' %>
  </div>
</div>